GLEW_INCLUDE = /opt/local/include
GLEW_LIB = /opt/local/lib
CC_FLAGS = -Wall -Wextra -ansi -pedantic

flag: file-util.o gl-util.o meshes.o flag.o
	gcc $(CC_FLAGS) -o flag $^ -framework GLUT -framework OpenGL -L$(GLEW_LIB) -lGLEW

.c.o:
	gcc $(CC_FLAGS) -c -o $@ $< -I$(GLEW_INCLUDE)

clean:
	rm -f flag *.o
